# select this to have a console app like
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y

# select this to have a virtual uart device like
# CONFIG_UART_NATIVE_PTY_0_ON_OWN_PTY=y
# Turn on the emulation framework. That in turn auto-enables CONFIG_I2C_EMUL,
# because native_sim.dts already declares an i2c-emul-controller and the
# driver is `default y` once the node exists.
CONFIG_EMUL=y
