CONFIG_GPIO=y
CONFIG_PRINTK=y
# We don't enable GPIO_EMUL here because this is the global config. 
# We will enable it specifically for the test target later.

CONFIG_I2C=y
CONFIG_BME280=y
CONFIG_SENSOR=y