name: Hello_CI

on:
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    container:
      image: ghcr.io/royyandzakiy/zephyr-devcontainer-ci:z4.4.2-sdk1.0.1

    env:
      ZEPHYR_VERSION: v4.4.2
      ZEPHYR_TOOLCHAIN_VERSION: 1.0.1
      BOARD_TYPE: "native_sim/native"

    steps:
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ env.BOARD_TYPE }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ env.BOARD_TYPE }}-

      - name: Build minimal hello world
        env:
          CCACHE_DIR: ~/.cache/ccache
        run: |
          west build -b $BOARD_TYPE $ZEPHYR_BASE/samples/basic/minimal -d build -p -- -DZEPHYR_SCACHE=ccache

      - name: Run hello world
        run: |
          timeout 10s ./build/zephyr/zephyr.exe || true

      - name: Show ccache stats
        if: always()
        run: |
          ccache -s || true